server:
  port: 8282

spring:
  application:
    name: JuHeDemo

  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:53306/XUZ_DEMO
    driver-Class-Name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  # Redis配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
    # 连接超时时间（毫秒）
    timeout: 5000

# mybatis配置
mybatis:
  type-aliases-package: com.xuz.pojo
  mapper-locations: classpath:mapper/*.xml
  # 表字段映射
  configuration:
    map-underscore-to-camel-case: true

